basic:
  num_demos:  8
  reward_filter: False
  hidden_size: 256
  demo_max_steps: 999
  algo: bc
  epochs: 3
  mini_batch_size: 512
  learning_rate: 0.0005
  l2_coef: 0.001
  entropy_coef: 0.001
  demo_seed_sampling: fixed