easy:
    n_envs: 64
    n_steps: 256
    n_checkpoints: 10
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo
    architecture: ResNet
    recurrent: False
    hidden_size: 256

tiny:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 4
    mini_batch_size: 512
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo
    architecture: ResNet
    recurrent: False
    hidden_size: 256

tiny_demo_il:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo_demo_il
    architecture: ResNet
    recurrent: False
    hidden_size: 256
    demo_coef: 0.5
    demo_learning_rate: 0.0005
    demo_batch_size: 128
    demo_mini_batch_size: 128
    demo_epochs: 10
    hot_start: 10
    buffer_max_samples: 100
    num_demos: 10
    demo_schedule: linear
    demo_learn_ratio: 0.1

tiny_demo_imp_samp:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo_demo_imp_samp
    architecture: ResNet
    recurrent: False
    hidden_size: 256
    demo_coef: 0.5
    demo_learning_rate: 0.0005
    demo_batch_size: 64
    demo_mini_batch_size: 64
    demo_epochs: 10
    hot_start: 10
    buffer_max_samples: 100
    num_demos: 10
    demo_schedule: linear
    demo_learn_ratio: 0.5

