easy:
    n_envs: 64
    n_steps: 256
    n_checkpoints: 10
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo
    architecture: ResNet
    recurrent: False
    hidden_size: 256

tiny:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 4
    mini_batch_size: 512
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo
    architecture: ResNet
    recurrent: False
    hidden_size: 256

tiny_hippo_schedule:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: hippo
    architecture: ResNet
    recurrent: False
    hidden_size: 256
    demo_coef: 0.5
    demo_learning_rate: 0.0005
    demo_batch_size: 64
    demo_mini_batch_size: 32
    demo_epochs: 10
    demo_controller: linear_schedule
    demo_learn_ratio: 0.5
    demo_entropy_coef: 0.01
    demo_value_coef: 0.005
    demo_max_steps: 18
    num_learn_demos: 2
    pre_load: 5
    pre_load_seed_sampling: fixed
    demo_levels: 5
    buffer_max_samples: 5
    store_mode: True
    demo_store_max_samples: 5
    replace: 0
    demo_sampling: random
    demo_normalise_adv: False
    demo_lr_schedule: False

tiny_hippo_bandit:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: False
    normalise_reward: True
    use_gae: True
    algo: hippo
    architecture: ResNet
    recurrent: False
    hidden_size: 256
    demo_coef: 0.5
    demo_learning_rate: 0.0005
    demo_batch_size: 64
    demo_mini_batch_size: 32
    demo_epochs: 10
    demo_controller: bandit
    demo_learn_ratio: 0.5
    demo_entropy_coef: 0.01
    demo_value_coef: 0.005
    demo_max_steps: 20
    num_learn_demos: 5
    pre_load: 10
    pre_load_seed_sampling: fixed
    demo_levels: 5
    buffer_max_samples: 5
    store_mode: True
    demo_store_max_samples: 10
    demo_normalise_adv: False
    demo_lr_schedule: False
    temperature: 2
    mu: 0.1
    rho: 0.1

tiny_hippo_val_schedule:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: hippo
    architecture: ResNet
    recurrent: False
    hidden_size: 256
    demo_coef: 0.5
    demo_learning_rate: 0.0005
    demo_batch_size: 64
    demo_mini_batch_size: 32
    demo_epochs: 3
    demo_controller: value_loss_schedule
    demo_learn_ratio: 0.5
    demo_entropy_coef: 0.01
    demo_value_coef: 0.005
    demo_max_steps: 256
    reward_filter: False
    num_learn_demos: 5
    pre_load: 10
    pre_load_seed_sampling: fixed
    demo_levels: 10
    buffer_max_samples: 5
    store_mode: True
    demo_store_max_samples: 10
    replace: 0
    demo_normalise_adv: False
    demo_lr_schedule: False
    temperature: 10
    rho: 0.1

main_hippo_val_schedule:
    n_envs: 64
    n_steps: 256
    n_checkpoints: 3
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: hippo
    architecture: ResNet
    recurrent: False
    hidden_size: 256
    demo_coef: 0.5
    demo_learning_rate: 0.0005
    demo_batch_size: 512
    demo_mini_batch_size: 64
    demo_epochs: 3
    demo_controller: value_loss_schedule
    demo_learn_ratio: 0.1
    demo_entropy_coef: 0.01
    demo_value_coef: 0.005
    demo_max_steps: 256
    num_learn_demos: 32
    pre_load: 200
    pre_load_seed_sampling: fixed
    demo_levels: 200
    buffer_max_samples: 32
    store_mode: True
    demo_store_max_samples: 200
    demo_sampling: random
    demo_normalise_adv: False
    demo_lr_schedule: False
    temperature: 10
    rho: 0.1
