easy:
    n_envs: 64
    n_steps: 256
    n_checkpoints: 10
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo
    architecture: Small
    recurrent: False
    hidden_size: 256

tiny:
    n_envs: 2
    n_steps: 16
    n_checkpoints: 2
    epoch: 3
    mini_batch_per_epoch: 4
    mini_batch_size: 512
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalise_adv: True
    normalise_reward: True
    use_gae: True
    algo: ppo
    architecture: small
    recurrent: False
    hidden_size: 256
